'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Pause,Play} from 'lucide-react';
import {url,words,type Lang} from '@/lib/catalog';
export function Preloader(){
  const [done,setDone]=useState(false);
  useEffect(()=>{
    const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const navigation=performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming|undefined;
    let seen=false;
    try{seen=sessionStorage.getItem('erasflans-intro-v3')==='1';sessionStorage.setItem('erasflans-intro-v3','1')}catch{}
    if(reduced||(seen&&navigation?.type!=='reload')){setDone(true);return}
    const timer=setTimeout(()=>setDone(true),900);
    return ()=>clearTimeout(timer);
  },[]);
  return <div className={'preloader preloader-v3'+(done?' preloader-done':'')} aria-hidden="true"><div className="preloader-lockup"><span className="preloader-monogram">e<span>.</span></span><div className="preloader-wordmark">erasflans<span>STAINLESS STEEL</span></div><div className="preloader-track"><span/></div></div></div>
}
export default function Hero({lang}:{lang:Lang}){const tr=lang==='tr';const video=useRef<HTMLVideoElement>(null);const [playing,setPlaying]=useState(false);const [ready,setReady]=useState(false);const [canPlay,setCanPlay]=useState(false);useEffect(()=>{const motion=matchMedia('(prefers-reduced-motion: reduce)');const screen=matchMedia('(min-width: 900px)');const connection=(navigator as Navigator & {connection?:{saveData?:boolean}}).connection;const sync=()=>{const enabled=screen.matches&&!motion.matches&&!connection?.saveData;setCanPlay(enabled);if(!enabled)video.current?.pause()};sync();motion.addEventListener('change',sync);screen.addEventListener('change',sync);return ()=>{motion.removeEventListener('change',sync);screen.removeEventListener('change',sync)}},[]);return <section className="hero-cinematic"><img className="hero-backdrop" src="/images/cnc-poster-v3.webp" alt="" width={1280} height={720} fetchPriority="high"/>{canPlay&&<video className={"hero-video"+(ready?" is-ready":"")} ref={video} src="/images/cnc-motion-v3.mp4" autoPlay muted loop playsInline preload="none" poster="/images/cnc-poster-v3.webp" aria-hidden="true" onPlaying={()=>{setPlaying(true);setReady(true)}} onPause={()=>setPlaying(false)} onError={()=>{setCanPlay(false);setReady(false)}}/>}<div className="hero-shade"/><div className="hero-content"><p className="hero-kicker">{tr?'HASSAS İŞLEME. GÜÇLÜ BAĞLANTILAR.':'PRECISION MACHINING. STRONG CONNECTIONS.'}</p><h1>{tr?'PASLANMAZ':'STAINLESS STEEL'}<br/>{tr?'FLANŞ':'FLANGE'}<br/><span>{tr?'ÜRETİMİ.':'MANUFACTURING.'}</span></h1><p className="hero-description">{tr?'Standart bağlantılardan özel tasarımlara. Endüstrinin ihtiyaçlarına göre şekillenen paslanmaz flanş çözümleri.':'From standard connections to custom designs. Stainless steel flange solutions shaped around the needs of industry.'}</p><div className="actions"><a className="button" href={url(lang,'contact')}>{words[lang].quote}<ArrowUpRight size={18}/></a><a className="button button-outline" href={url(lang,'products')}>{words[lang].explore}<ArrowRight size={18}/></a></div><div className="hero-thumbnails">{['/images/cnc-poster-v3.webp','/images/flange-editorial-v3.webp','/images/cnc-detail-v3.webp'].map((src,n)=><a href={url(lang,'products')} key={n} aria-label={tr?'Paslanmaz flanş ürünlerini keşfedin':'Explore stainless steel flange products'}><img src={src} width={480} height={272} alt={tr?'Paslanmaz flanş ve üretim görseli '+(n+1):'Stainless steel flange and manufacturing visual '+(n+1)} loading="lazy"/></a>)}</div></div>{canPlay&&<button className="video-control" onClick={()=>{if(!video.current)return;if(playing)video.current.pause();else void video.current.play().catch(()=>setPlaying(false))}} aria-label={playing?(tr?'Videoyu duraklat':'Pause video'):(tr?'Videoyu oynat':'Play video')}>{playing?<Pause size={16}/>:<Play size={16}/>}<span>{playing?(tr?'Duraklat':'Pause'):(tr?'Oynat':'Play')}</span></button>}</section>}

