import {ArrowUpRight} from 'lucide-react';
import {url,words,type Lang} from '@/lib/catalog';
const groups=[
{id:'cnc-lathes',tr:'CNC dik ve yatay tornalar',en:'CNC vertical and horizontal lathes',items:[['CNC dik torna','CNC vertical lathe','Ø3400 × 1500 mm'],['CNC dik torna','CNC vertical lathe','Ø1400 × 1000 mm'],['CNC torna','CNC lathe','Ø300 × 1500 mm'],['CNC torna','CNC lathe','Ø300 × 2000 mm'],['CNC torna','CNC lathe','12 inç','12 inch'],['CNC torna','CNC lathe','18 inç','18 inch']]},
{id:'machining-centers',tr:'CNC işleme merkezleri',en:'CNC machining centers',items:[['CNC işleme merkezi','CNC machining center','1000 × 600 mm'],['CNC işleme merkezi','CNC machining center','2500 × 1000 mm']]},
{id:'universal-lathes',tr:'Üniversal tornalar',en:'Universal lathes',items:[['Üniversal torna','Universal lathe','Ø890 × 4000 mm'],['Üniversal torna','Universal lathe','Ø1000 × 4000 mm'],['Üniversal torna','Universal lathe','Ø600 × 2000 mm'],['Üniversal torna','Universal lathe','Ø600 × 1500 mm']]},
{id:'auxiliary',tr:'Yardımcı ekipman ve vinç',en:'Auxiliary equipment and crane',items:[['Radyal matkap','Radial drill',''],['MIG/MAG kaynak makinesi','MIG/MAG welding machine',''],['Elektrik ark kaynak makinesi','Arc welding machine',''],['Köprülü vinç','Overhead crane','10 ton','10 tonne']]}
];
export default function MachinePark({lang}:{lang:Lang}){const tr=lang==='tr';return <section className="section inner-section machine-park"><div className="page-intro"><h1>{tr?'Makine parkuru':'Machine park'}</h1><p>{tr?'CNC dik ve yatay tornalar, işleme merkezleri ve yardımcı ekipmanlarla paslanmaz flanş üretim altyapısı.':'Stainless steel flange production infrastructure with CNC vertical and horizontal lathes, machining centers and auxiliary equipment.'}</p></div><div className="machine-stats"><div><strong>16</strong><span>{tr?'Tezgâh ve yardımcı ekipman':'Machines and auxiliary units'}</span></div><div><strong>Ø3400 <small>mm</small></strong><span>{tr?'En büyük listelenen torna çapı':'Largest listed turning diameter'}</span></div><div><strong>10 <small>{tr?'ton':'tonne'}</small></strong><span>{tr?'Köprülü vinç kapasitesi':'Overhead crane capacity'}</span></div></div><nav className="machine-jumps" aria-label={tr?'Makine grupları':'Machine groups'}>{groups.map(g=><a key={g.id} href={'#'+g.id}>{g[lang]}</a>)}</nav><div className="machine-groups">{groups.map(g=><section id={g.id} key={g.id} className="machine-group"><div className="machine-group-heading"><h2>{g[lang]}</h2><span>{g.items.length} {tr?'ekipman':'units'}</span></div><ul>{g.items.map((item,i)=><li key={i}><span className="machine-count">01 ×</span><span className="machine-name">{item[tr?0:1]}</span>{item[2]&&<strong>{!tr&&item[3]?item[3]:item[2]}</strong>}</li>)}</ul></section>)}</div><section className="machine-support"><h2>{tr?'Kalite ve destek altyapısı':'Quality and supporting infrastructure'}</h2><div>{(tr?[
['Teknik kontrol laboratuvarı','Boyutsal ölçüm, yüzey pürüzlülüğü ve malzeme doğrulama süreçlerini destekleyen kontrol altyapısı.'],
['Üretim içi kontrol odası','Üretim akışına entegre ölçüm ve kontrol noktası. Kritik ölçüler, parça çizimine göre değerlendirilir.'],
['Takım ve fikstür stoğu','Flanşlara yönelik bağlama fikstürleri, takım tutucular ve hassas kesici uçlar.']
]:[
['Technical inspection laboratory','Inspection infrastructure supporting dimensional measurement, surface roughness and material verification.'],
['In-line inspection room','Measurement and inspection integrated into the production flow. Critical dimensions are assessed against the part drawing.'],
['Tooling and fixture stock','Flange-specific clamping fixtures, tool holders and precision cutting inserts.']]).map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></section><p className="machine-note">{tr?'Listelenen ölçüler tezgâh kapasitesini ifade eder. Parçanın üretilebilirliği; bağlama, geometri, malzeme ve toleranslara göre teknik çizim üzerinden teyit edilir.':'Listed dimensions describe machine capacity. Part manufacturability is confirmed from the drawing based on fixturing, geometry, material and tolerances.'}</p><a className="text-link" href={url(lang,'contact')}>{words[lang].quote}<ArrowUpRight size={18}/></a></section>}
