export type Lang='tr'|'en';
export const origin=(process.env.NEXT_PUBLIC_SITE_URL || (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : 'https://erasflans.sanliayumut463452.chatgpt.site')).replace(/\/$/,'');
export const contact={phone:'+90 506 098 14 05',tel:'+905060981405',email:'info@erflans.com',address:'Vezir Çiftliği Mahallesi, Dülger Sokak No:18/1, Başiskele / Kocaeli, Türkiye'};
export const words={tr:{home:'Ana sayfa',products:'Ürünler',alloys:'Paslanmaz kaliteleri',sectors:'Sektörler',about:'Kurumsal',capabilities:'Üretim kabiliyetleri',machines:'Makine parkuru',quality:'Kalite yaklaşımı',contact:'İletişim',quote:'Teklif alın',explore:'Ürünleri keşfedin',details:'Ürünü inceleyin',related:'İlgili ürünler'},en:{home:'Home',products:'Products',alloys:'Steel grades',sectors:'Industries',about:'About us',capabilities:'Capabilities',machines:'Machine park',quality:'Quality approach',contact:'Contact',quote:'Get a quote',explore:'Explore products',details:'View product',related:'Related products'}};
export const paths={tr:{products:'urunler',alloys:'paslanmaz-kaliteleri',sectors:'sektorler',about:'hakkimizda',capabilities:'uretim',machines:'makine-parkuru',quality:'kalite',contact:'iletisim'},en:{products:'products',alloys:'stainless-steel-grades',sectors:'industries',about:'about',capabilities:'capabilities',machines:'machine-park',quality:'quality',contact:'contact'}};
export type Section=keyof typeof paths.tr;
export function url(lang:Lang,section?:Section,slug?:string){return '/'+lang+(section?'/'+paths[lang][section]:'')+(slug?'/'+slug:'')}
export type Product={id:string;slug:Record<Lang,string>;name:Record<Lang,string>;tag:Record<Lang,string>;desc:Record<Lang,string>;detail:Record<Lang,string>;image:string};
const rows=[
['flat','duz-paslanmaz-flans','flat-stainless-steel-flange','Düz paslanmaz çelik flanş','Flat stainless steel flange','Düz yüzey bağlantısı','Flat face connection','product-duz-flans-BjysGo5i.webp','Boru bağlantılarında düz yüzeyli bir bağlantı geometrisi sunar. Delik düzeni ve et kalınlığı, karşı flanş ve conta ile birlikte değerlendirilir.','A flat face connection for pipe assemblies. Bolt pattern and plate thickness are evaluated alongside the mating flange and gasket.','Teklif için dış çap, iç çap, cıvata dairesi ve delik adedini paylaşın. Mevcut tesisata uyum için karşı parçanın ölçüleri de gereklidir.','Specify the outer diameter, bore, bolt circle and hole count. Dimensions of the mating component help establish compatibility with existing pipework.'],
['blind','kor-paslanmaz-flans','blind-stainless-steel-flange','Kör paslanmaz çelik flanş','Blind stainless steel flange','Hat sonu kapama','Pipeline end closure','product-kor-flans-WLuUmoEp.webp','Boru hattının veya ekipman açıklığının kapatılması için merkez deliği bulunmayan flanş tipidir. Sökülebilir bağlantısı bakım erişimini destekler.','A flange without a central bore for closing a pipeline or equipment opening. Its removable connection supports maintenance access.','Kapatılacak açıklık, conta yüzeyi ve çalışma koşullarını belirtin. Basınç ve sıcaklık gereksinimleri et kalınlığı değerlendirmesinin parçasıdır.','Specify the opening, gasket face and operating conditions. Pressure and material conditionature requirements are part of the thickness assessment.'],
['loose','hareketli-paslanmaz-flans','loose-stainless-steel-flange','Hareketli paslanmaz çelik flanş','Loose stainless steel flange','Serbest dönen bağlantı','Lap-joint connection','product-hareketli-flans-D2CwOQad.webp','Yaka veya bağlantı ucu ile birlikte kullanılan hareketli tasarım, montajda cıvata deliklerinin hizalanmasına yardımcı olur.','A loose design used with a collar or stub end to help align bolt holes during assembly.','Flanşın yanı sıra yaka ölçüsünü, boru çapını ve bağlantı yüzeyini paylaşın. Takımın bir bütün olarak ölçülendirilmesi doğru eşleşmeyi sağlar.','Provide collar dimensions, pipe diameter and the connection face. Dimensioning the full assembly helps establish the correct fit.'],
['jis','jis-paslanmaz-flans','jis-stainless-steel-flange','JIS paslanmaz çelik flanş','JIS stainless steel flange','Japon bağlantı ölçüleri','Japanese connection dimensions','product-jis-normu-flans-Y0ZGHqEP.webp','JIS bağlantı geometrisi istenen projeler için paslanmaz çelik flanş seçeneğidir. Ölçü serisi ve karşı parça bilgileri sipariş öncesinde eşleştirilir.','A stainless steel flange option for projects specifying JIS connection geometry. Dimensional series and mating parts are matched before ordering.','Sadece nominal çap yeterli değildir; JIS standardının numarası, basınç sınıfı ve yüzey tipini teknik talebe ekleyin.','Nominal diameter alone is insufficient. Include the JIS standard number, pressure designation and facing in the technical enquiry.'],
['threaded','disli-paslanmaz-flans','threaded-stainless-steel-flange','Dişli paslanmaz çelik flanş','Threaded stainless steel flange','Vidalı boru bağlantısı','Threaded pipe connection','product-disli-flans-IfpplS-C.webp','İç diş üzerinden bağlantı kuran bu ürün, dişli boru veya ekipman bağlantısı gerektiren montajlar için değerlendirilir.','This internally threaded product is considered for assemblies requiring a threaded pipe or equipment connection.','Diş standardı, adımı, çapı ve diş boyu birlikte belirtilmelidir. Sızdırmazlık yöntemi ve akışkan uyumu uygulamaya göre değerlendirilir.','Specify the thread standard, pitch, diameter and engagement length. Sealing method and fluid compatibility depend on the application.'],
['neck','kaynak-boyunlu-paslanmaz-flans','weld-neck-stainless-steel-flange','Kaynak boyunlu paslanmaz çelik flanş','Weld neck stainless steel flange','Boyunlu bağlantı geometrisi','Weld neck geometry','product-kaynak-boyunlu-flans.webp','Boruya kaynak bağlantısı için boyun bölgesi bulunan flanş tipidir. Boyun ve boru et kalınlığının eşleşmesi teknik değerlendirmede önemlidir.','A flange with a neck section for a welded pipe connection. Matching the neck and pipe wall thickness is an important design consideration.','Boru dış çapı, et kalınlığı, kaynak ağzı ve alaşım bilgisini iletin. Kaynak yöntemi ve servis koşulları birlikte ele alınmalıdır.','Supply pipe outer diameter, wall thickness, weld preparation and alloy. Welding procedure and service conditions should be considered together.'],
['exhaust','egzoz-paslanmaz-flans','exhaust-stainless-steel-flange','Egzoz paslanmaz çelik flanşı','Stainless steel exhaust flange','Çizime özel bağlantı','Drawing-specific connection','product-egzoz-flans-z68KQgHL.webp','Egzoz bağlantı geometrisine göre işlenen flanş ailesidir. Delik konumları, port şekli ve montaj alanı teknik çizime göre tanımlanır.','A flange family machined to exhaust connection geometry. Hole positions, port shape and mounting envelope are defined by the drawing.','Paslanmaz çelikun uygunluğu çalışma sıcaklığına bağlıdır. Sürekli ve tepe sıcaklıkları belirtilmeden malzeme seçimi kesinleştirilmez.','Stainless steel suitability depends on operating material conditionature. Continuous and peak material conditionatures are required before material selection is finalised.'],
['square','kare-paslanmaz-flans','square-stainless-steel-flange','Kare paslanmaz çelik flanş','Square stainless steel flange','Kare bağlantı profili','Square mounting profile','product-kare-flans-C8a7ZGrJ.webp','Dairesel dış profil yerine kare montaj alanı sunan flanş tipidir. Ekipman bağlantıları ve özel yerleşimler için çizime göre hazırlanır.','A flange with a square mounting envelope instead of a circular outer profile. It is prepared to drawing for equipment connections and custom layouts.','Dış boyutlar, köşe radyüsleri, merkez açıklığı ve bağlantı deliklerini belirtin. Montaj alanının sınırları çizimde gösterilmelidir.','Specify outer dimensions, corner radii, central opening and fixing holes. Show the available mounting envelope on the drawing.'],
['dublin','dublin-paslanmaz-flans','dublin-stainless-steel-flange','Dublin paslanmaz çelik flanş','Dublin stainless steel flange','Tanker bağlantı geometrisi','Tanker connection geometry','product-dublin-flans.webp','Tank ve tanker bağlantılarında talep edilen Dublin tip geometriler için ürün grubudur. Karşı bağlantının ölçüleri üzerinden değerlendirilir.','A product group for Dublin-type geometries requested in tank and tanker connections. Assessment uses the mating connection dimensions.','Bağlantı tipi, conta yuvası ve kapak ölçülerini teknik çizimle paylaşın. Mevcut parçanın ölçülü numunesi de değerlendirmeye yardımcı olur.','Share the connection type, gasket recess and cover dimensions in a technical drawing. A dimensioned sample also helps the assessment.'],
['collar','yaka-paslanmaz-flans','collar-stainless-steel-flange','Yaka paslanmaz çelik flanş','Collar stainless steel flange','Yaka ve boru eşleşmesi','Collar and pipe assembly','product-yaka-flans-Mjpm00N1.webp','Yaka geometrisiyle tanımlanan bu ürün grubu, boru ve hareketli flanş takımlarının eşleşmesinde kullanılır.','Defined by its collar geometry, this product group is used to match pipe and loose-flange assemblies.','Yaka çapı, boyu, oturma yüzeyi ve boru et kalınlığı birlikte değerlendirilir. Teknik çizimde eş çalışan parçaları da belirtin.','Collar diameter, length, seating face and pipe wall thickness are evaluated together. Include mating components in the technical drawing.'],
['en','en-1092-paslanmaz-flans','en-1092-stainless-steel-flange','EN bağlantılı paslanmaz çelik flanş','EN-pattern stainless steel flange','Avrupa bağlantı geometrisi','European connection geometry','product-en-1092-1-aluminyum-flans-L_vGZWzX.webp','EN bağlantı ölçüleri istenen projeler için paslanmaz çelik flanş ailesidir. Çelik flanşlar için EN 1092-1 kapsamı, malzeme kalitesi ve basınç-sıcaklık gereksinimleriyle birlikte değerlendirilir.','A stainless steel flange family for projects requesting EN connection dimensions. EN 1092-1 covers steel flanges; material grade and pressure-material conditionature requirements must also be assessed.','EN 1092-1 bağlantılarında flanş tipi, PN sınıfı ve yüzey formu belirtilmelidir. Talep edilen bağlantı ölçüleri ve geçerli malzeme standardı teknik teklifte ayrı ayrı netleştirilir.','Specify flange type, PN designation and facing for EN 1092-1 connections. Requested connection dimensions and the applicable material standard are clarified separately in the technical quotation.'],
['ansi','ansi-paslanmaz-flans','ansi-stainless-steel-flange','ANSI ölçülü paslanmaz çelik flanş','ANSI-pattern stainless steel flange','Amerikan bağlantı geometrisi','American connection geometry','product-ansi-b16-5-aluminyum-flans-ClDbiV-w.webp','ANSI / ASME bağlantı ölçüleri talep edilen sistemlere yönelik ürün grubudur. Class tanımı ve bağlantı yüzeyi, talep edilen ölçü setinin parçasıdır.','A product group for systems requesting ANSI / ASME connection dimensions. Class designation and facing form part of the requested dimensional specification.','Ölçü uyumu, malzeme ve basınç uygunluğunun yerine geçmez. İlgili standart sürümü, alaşım ve çalışma koşulları teknik değerlendirmede birlikte ele alınır.','Dimensional compatibility does not establish material or pressure suitability. Standard edition, alloy and operating conditions are assessed together.'],
['din','din-paslanmaz-flans','din-stainless-steel-flange','DIN paslanmaz çelik flanş','DIN stainless steel flange','DIN bağlantı ölçüleri','DIN connection dimensions','product-din-aluminyum-flans-D6w2z2Cr.webp','DIN bağlantı ölçülerine sahip mevcut tesisat ve ekipmanlarla eşleşmesi istenen paslanmaz çelik flanş grubudur.','A stainless steel flange group for matching existing pipework and equipment with DIN connection dimensions.','DIN numarası, nominal çap, delik sayısı ve conta yüzeyini belirtin. Mevcut flanş çizimi veya ölçülü numune, doğru ürün seçimini kolaylaştırır.','Specify the DIN number, nominal diameter, hole count and gasket face. An existing drawing or dimensioned sample helps select the correct product.'],
['custom','ozel-paslanmaz-flans','custom-stainless-steel-flange','Özel paslanmaz çelik flanş','Custom stainless steel flange','Teknik çiziminize göre','Made to your drawing','product-ozel-aluminyum-flans-CRrjt7gp.webp','Standart ürün ölçülerinin dışında kalan bağlantılar için teknik çizime dayalı paslanmaz çelik flanş üretimidir. Geometri, delikler ve yüzeyler projeye göre ele alınır.','Drawing-based stainless steel flange production for connections outside standard product dimensions. Geometry, holes and surfaces are assessed for the project.','PDF, DWG veya STEP dosyanıza alaşım, adet, kritik toleranslar ve yüzey beklentisini ekleyin. Üretilebilirlik değerlendirmesinin ardından teknik teklif hazırlanır.','Include alloy, quantity, critical tolerances and finish requirements with your PDF, DWG or STEP file. A technical quotation follows the manufacturability review.']
];
export const products:Product[]=rows.map(r=>({id:r[0],slug:{tr:r[1],en:r[2]},name:{tr:r[3],en:r[4]},tag:{tr:r[5],en:r[6]},image:'/images/'+r[7],desc:{tr:r[8],en:r[9]},detail:{tr:r[10],en:r[11]}}));
export const alloys=[
  {
    "id": "316",
    "name": {
      "tr": "Molibden alaşımlı paslanmaz",
      "en": "Molybdenum-alloyed stainless steel"
    },
    "desc": {
      "tr": "AISI 316 paslanmaz, molibden içeren östenitik bir çelik kalitesidir. Flanş seçiminde akışkan bileşimi, konsantrasyon, sıcaklık ve bağlantı standardı birlikte değerlendirilir.",
      "en": "AISI 316 stainless steel is a molybdenum-alloyed austenitic grade. Fluid composition, concentration, material conditionature and connection standard are assessed together for flange selection."
    }
  },
  {
    "id": "310",
    "name": {
      "tr": "Isıl koşullara göre seçim",
      "en": "Selection for thermal service"
    },
    "desc": {
      "tr": "AISI 310 paslanmaz flanş taleplerinde sürekli ve tepe sıcaklığı, ısıl çevrimler ve çalışma atmosferi belirtilmelidir. Nihai uygunluk malzeme belgesi ve proje şartnamesiyle değerlendirilir.",
      "en": "AISI 310 stainless steel flange enquiries should specify continuous and peak material conditionatures, thermal cycling and the operating atmosphere. Final suitability is assessed against material documentation and project specifications."
    }
  },
  {
    "id": "304",
    "name": {
      "tr": "Genel endüstriyel bağlantılar",
      "en": "General industrial connections"
    },
    "desc": {
      "tr": "AISI 304 paslanmaz, östenitik bir çelik kalitesidir. Endüstriyel bağlantılarda çalışma ortamı, kaynak gereksinimi, yüzey kalitesi ve ölçüler birlikte değerlendirilir.",
      "en": "AISI 304 stainless steel is an austenitic grade. Industrial connections require assessment of service environment, welding requirements, finish and dimensions."
    }
  }
];
const sectorRows=[['denizcilik','marine','Denizcilik','Marine','Tuzlu su ortamı, boru hattı bağlantıları ve bakım erişimi.','Saltwater environment, piping connections and maintenance access.'],['tersane','shipbuilding','Tersane','Shipbuilding','Yeni inşa ve bakım projelerinde teknik çizime uygun bağlantılar.','Drawing-based connections for new construction and maintenance.'],['enerji','energy','Enerji','Energy','Enerji ekipmanlarında çalışma koşullarına göre ölçülendirilen bağlantılar.','Connections dimensioned for the service conditions of energy equipment.'],['makine','machinery','Makine','Machinery','Ekipman arayüzleri, montaj delikleri ve kritik toleranslar.','Equipment interfaces, mounting holes and critical tolerances.'],['gida','food-industry','Gıda endüstrisi','Food industry','Akışkan, temizlik koşulları ve yüzey gereksinimlerine göre seçim.','Selection based on fluid, cleaning conditions and surface requirements.'],['yakit-tanklari','fuel-tanks','Yakıt tankları','Fuel tanks','Tank girişleri, kapama noktaları ve sökülebilir bağlantılar.','Tank inlets, closures and removable connections.'],['yakit-tankerleri','fuel-tankers','Yakıt tankerleri','Fuel tankers','Taşıma koşulları ve karşı ekipmanla eşleşen bağlantı geometrileri.','Connection geometries matched to transport conditions and mating equipment.'],['lpg-tanklari','lpg-tanks','LPG tankları','LPG tanks','Basınç, sıcaklık ve tasarım şartnamesine göre teknik değerlendirme.','Technical assessment against pressure, material conditionature and design specifications.'],['lpg-tankerleri','lpg-tankers','LPG tankerleri','LPG tankers','Taşıma ekipmanının tasarım ve mevzuat gereksinimlerine göre değerlendirme.','Assessment against the transport equipment design and regulatory requirements.'],['gida-tanklari','food-tanks','Gıda tankları','Food tanks','Malzeme uyumu, yüzey kalitesi ve temizlenebilirlik gereksinimleri.','Material compatibility, surface quality and cleanability requirements.'],['gida-tankerleri','food-tankers','Gıda tankerleri','Food tankers','Sökülebilir bağlantılarda conta ve yüzey eşleşmesi.','Gasket and face matching for removable connections.'],['egzoz','exhaust','Egzoz sistemleri','Exhaust systems','Port geometrisi ve çalışma sıcaklığına göre malzeme değerlendirmesi.','Material assessment against port geometry and operating material conditionature.'],['kimya','chemical','Kimya endüstrisi','Chemical industry','Akışkan bileşimi ve konsantrasyona göre korozyon uyumu değerlendirmesi.','Corrosion compatibility assessment against fluid composition and concentration.'],['su-sistemleri','water-systems','Su sistemleri','Water systems','Su arıtma ve dağıtım ekipmanları için bağlantı ölçüleri.','Connection dimensions for water treatment and distribution equipment.'],['altyapi','infrastructure','Altyapı','Infrastructure','Proje şartnamelerine uygun ekipman ve hat bağlantıları.','Equipment and pipeline connections aligned with project specifications.']];
export const sectors=sectorRows.map(r=>({slug:{tr:r[0],en:r[1]},name:{tr:r[2],en:r[3]},desc:{tr:r[4],en:r[5]}}));
export type Route={section?:Section,product?:Product,alloy?:typeof alloys[number],sector?:typeof sectors[number]};
export function resolve(lang:Lang,slug:string[]):Route|null{if(!slug.length)return {};const section=(Object.keys(paths[lang]) as Section[]).find(k=>paths[lang][k]===slug[0]);if(!section||slug.length>2)return null;if(slug.length===1)return {section};if(section==='products'){const product=products.find(p=>p.slug[lang]===slug[1]);return product?{section,product}:null}if(section==='alloys'){const alloy=alloys.find(p=>p.id===slug[1]);return alloy?{section,alloy}:null}if(section==='sectors'){const sector=sectors.find(p=>p.slug[lang]===slug[1]);return sector?{section,sector}:null}return null}
export function routeUrl(lang:Lang,r:Route){return url(lang,r.section,r.product?.slug[lang]||r.alloy?.id||r.sector?.slug[lang])}
export function allRoutes():Route[]{return [{},...(Object.keys(paths.tr) as Section[]).map(section=>({section})),...products.map(product=>({section:'products' as const,product})),...alloys.map(alloy=>({section:'alloys' as const,alloy})),...sectors.map(sector=>({section:'sectors' as const,sector}))]}
